// INCLUDE
#include "./text.hpp"
#include "../interface.hpp"


// CODE
u16string to_u16string(int number)
{
  wstring_convert< codecvt_utf8_utf16<char16_t, 0x10ffff, little_endian>, char16_t > conversion;
  return conversion.from_bytes( to_string(number) );
}

void initialise_font (colour font_colour)
{
    u16string id_addition = to_u16string(font_colour.red) + to_u16string(font_colour.green) + to_u16string(font_colour.blue);

    if (has_character(u"NULL" + id_addition)) throw runtime_error("\nERROR: A font with the colour" + to_string(font_colour.red) + "," + to_string(font_colour.green) + "," + to_string(font_colour.blue) + " already exists.");

    set_default_shape_colour(font_colour);

    float thickness = 0.05;
    float line_thickness = 2 * thickness;
    string shape_id_addition = to_string(font_colour.red) + to_string(font_colour.green) + to_string(font_colour.blue);

    // OPTIMISE: characters are not made for rotation, rotations will cause glitchy appearance

    set_character(u"NULL" + id_addition, &shape("character-NULL" + shape_id_addition).width(0.5).height(0.8).subtract(&shape("character-NULL-" + shape_id_addition).width(0.3).height(0.6)).build());
    set_character(u" " + id_addition, &shape("character- " + shape_id_addition).build());
    set_character(u"\t" + id_addition, &shape("character-\t" + shape_id_addition).build());
    set_character(u"\n" + id_addition, &shape("character-\n" + shape_id_addition).build());
    set_character(u"a" + id_addition, &shape("character-a" + shape_id_addition).radius(0.2).height(0.05).thickness(thickness).y(-0.125).add(&shape("character-a-" + shape_id_addition).height(0.55).width(line_thickness).y(-0.125).x(0.2)).build());
    set_character(u"b" + id_addition, &shape("character-b" + shape_id_addition).radius(0.2).height(0.05).thickness(thickness).y(-0.125).add(&shape("character-b-" + shape_id_addition).height(0.8).width(line_thickness).x(-0.2)).build());
    set_character(u"c" + id_addition, &shape("character-c" + shape_id_addition).radius(0.2).height(0.05).thickness(thickness).y(-0.125).subtract(&shape("character-c-" + shape_id_addition).rotate(45.0).width(0.3).height(0.3).x(0.25).y(-0.125)).build());
    set_character(u"d" + id_addition, &shape("character-d" + shape_id_addition).radius(0.2).height(0.05).thickness(thickness).y(-0.125).add(&shape("character-d-" + shape_id_addition).height(0.8).width(line_thickness).x(0.2)).build());
    set_character(u"e" + id_addition, &shape("character-e" + shape_id_addition).radius(0.2).height(0.05).thickness(thickness).y(-0.125).subtract(&shape("character-e-" + shape_id_addition).width(0.3).height(0.2).x(0.25).y(-0.15)).add(&shape("character-e--" + shape_id_addition).height(line_thickness).width(0.4).y(-0.1).x(0.045)).build());
    set_character(u"f" + id_addition, &shape("character-f" + shape_id_addition).width(0.5).height(1.0).round(0.1).thickness(thickness).x(0.25).y(-0.15).intersect(&shape("character-f-" + shape_id_addition).height(0.8).width(0.3).x(0.05)).add(&shape("character-f--" + shape_id_addition).height(line_thickness).width(0.8).y(0.1).intersect(&shape("character-f---" + shape_id_addition).height(0.8).width(0.3))).build());
    set_character(u"g" + id_addition, &shape("character-g" + shape_id_addition).height(0.8).radius(0.2).thickness(thickness).subtract(&shape("character-g-" + shape_id_addition).height(1.0).width(1.0).y(0.65)).subtract(&shape("character-g--" + shape_id_addition).height(0.9).width(0.5).x(-0.2)).add(&shape("character-g---" + shape_id_addition).radius(0.2).height(0.05).thickness(thickness).y(-0.125)).build());
    set_character(u"h" + id_addition, &shape("character-h" + shape_id_addition).radius(0.2).height(0.4).thickness(thickness).y(-0.3).intersect(&shape("character-h-" + shape_id_addition).height(0.8).width(0.5)).add(&shape("character-h--" + shape_id_addition).height(0.8).width(line_thickness).x(-0.2)).build());
    set_character(u"i" + id_addition, &shape("character-i" + shape_id_addition).width(line_thickness).height(0.5).y(-0.15).add(&shape("character-i-" + shape_id_addition).width(line_thickness).height(line_thickness).y(0.25)).add(&shape("character-i--" + shape_id_addition).width(0.3).height(line_thickness).y(-0.35)).add(&shape("character-i---" + shape_id_addition).width(0.15).height(line_thickness).y(0.05).x(-0.075)).build());
    set_character(u"j" + id_addition, &shape("character-j" + shape_id_addition).width(line_thickness).height(line_thickness).y(0.25).x(0.05).add(&shape("character-j-" + shape_id_addition).width(0.15).height(line_thickness).y(0.05).x(-0.025)).add(&shape("character-j--" + shape_id_addition).width(0.5).height(1.0).round(0.1).thickness(thickness).x(-0.2).y(-0.1).intersect(&shape("character-j---" + shape_id_addition).height(0.8).width(0.3).y(-0.3).x(0.05))).build());
    set_character(u"k" + id_addition, &shape("character-k" + shape_id_addition).height(0.8).width(line_thickness).x(-0.2).add(&shape("character-k-" + shape_id_addition).width(1.0).height(line_thickness).rotate(45.0).x(-0.025).intersect(&shape("character-k--" + shape_id_addition).height(0.45).width(0.5).y(-0.05))).add(&shape("character-k---" + shape_id_addition).width(1.0).height(line_thickness).rotate(-45.0).y(-0.2).x(-0.025).intersect(&shape("character-k----" + shape_id_addition).height(0.35).width(0.5).y(-0.225))).build());
    set_character(u"l" + id_addition, &shape("character-l" + shape_id_addition).width(0.5).height(1.0).round(0.1).thickness(thickness).x(0.25).y(0.15).intersect(&shape("character-l-" + shape_id_addition).height(0.8).width(0.3).x(0.05)).add(&shape("character-l--" + shape_id_addition).height(line_thickness).width(0.2).y(0.35).x(-0.1)).build());
    set_character(u"m" + id_addition, &shape("character-m" + shape_id_addition).radius(0.1).height(0.4).thickness(thickness).y(-0.2).x(-0.1).intersect(&shape("character-m-" + shape_id_addition).height(0.8).width(0.5)).add(&shape("character-m--" + shape_id_addition).radius(0.1).height(0.4).thickness(thickness).y(-0.2).x(0.1).intersect(&shape("character-m---" + shape_id_addition).height(0.8).width(0.5))).add(&shape("character-m----" + shape_id_addition).height(0.55).width(line_thickness).y(-0.125).x(-0.2)).build());
    set_character(u"n" + id_addition, &shape("character-n" + shape_id_addition).radius(0.2).height(0.4).thickness(thickness).y(-0.3).intersect(&shape("character-n-" + shape_id_addition).height(0.8).width(0.5)).add(&shape("character-n--" + shape_id_addition).height(0.55).width(line_thickness).y(-0.125).x(-0.2)).build());
    set_character(u"o" + id_addition, &shape("character-o" + shape_id_addition).radius(0.2).height(0.05).thickness(thickness).y(-0.125).build());
    set_character(u"p" + id_addition, &shape("character-p" + shape_id_addition).radius(0.2).height(0.05).thickness(thickness).y(-0.125).add(&shape("character-p-" + shape_id_addition).height(0.8).width(line_thickness).x(-0.2).y(-0.25)).build());
    set_character(u"q" + id_addition, &shape("character-q" + shape_id_addition).radius(0.2).height(0.05).thickness(thickness).y(-0.125).add(&shape("character-q-" + shape_id_addition).height(0.8).width(line_thickness).x(0.2).y(-0.25)).build());
    set_character(u"r" + id_addition, &shape("character-r" + shape_id_addition).radius(0.2).height(0.4).width(0.4).thickness(thickness).y(-0.3).x(0.25).intersect(&shape("character-r-" + shape_id_addition).height(0.8).width(0.4)).add(&shape("character-r--" + shape_id_addition).height(0.55).width(line_thickness).y(-0.125).x(-0.15)).build());
    set_character(u"s" + id_addition, &shape("character-s" + shape_id_addition).radius(0.1125).width(0.5).thickness(thickness).y(-0.2375).x(-0.1625).intersect(&shape("character-s-" + shape_id_addition).width(0.5).height(0.8)).subtract(&shape("character-s--" + shape_id_addition).width(0.5).height(0.15).x(-0.275).y(-0.1)).add(&shape("character-s---" + shape_id_addition).radius(0.1125).width(0.5).thickness(thickness).y(-0.0125).x(0.1625).intersect(&shape("character-s----" + shape_id_addition).width(0.5).height(0.8)).subtract(&shape("character-s-----" + shape_id_addition).width(0.5).height(0.15).x(0.275).y(-0.1))).build());
    set_character(u"t" + id_addition, &shape("character-t" + shape_id_addition).width(0.5).height(1.0).round(0.1).thickness(thickness).x(0.2).y(0.15).intersect(&shape("character-t-" + shape_id_addition).height(0.8).width(0.3)).add(&shape("character-t--" + shape_id_addition).height(line_thickness).width(0.35).y(0.2).x(-0.0)).build());
    set_character(u"u" + id_addition, &shape("character-u" + shape_id_addition).radius(0.2).height(0.4).thickness(thickness).y(0.05).subtract(&shape("character-u-" + shape_id_addition).width(0.8).height(0.5).y(0.4)).add(&shape("character-u--" + shape_id_addition).height(0.55).width(line_thickness).y(-0.125).x(0.2)).build());
    set_character(u"v" + id_addition, &shape("character-v" + shape_id_addition).height(2.0).width(line_thickness).rotate(20.0).y(-0.4).intersect(&shape("character-v-" + shape_id_addition).width(0.5).height(0.55).y(-0.125)).add(&shape("character-v--" + shape_id_addition).height(2.0).width(line_thickness).rotate(-20.0).y(-0.4).intersect(&shape("character-v---" + shape_id_addition).width(0.5).height(0.55).y(-0.125))).build());
    set_character(u"w" + id_addition, &shape("character-w" + shape_id_addition).height(0.8).width(line_thickness).rotate(2.5).x(-0.2).intersect(&shape("character-w-" + shape_id_addition).height(0.55).width(0.5).y(-0.125)).add(&shape("character-w--" + shape_id_addition).height(0.8).width(line_thickness).rotate(-2.5).x(0.2).intersect(&shape("character-w---" + shape_id_addition).height(0.55).width(0.5).y(-0.125))).add(&shape("character-w----" + shape_id_addition).height(1.0).width(line_thickness).rotate(25.0).intersect(&shape("character-w-----" + shape_id_addition).width(0.45).height(0.4).y(-0.2))).add(&shape("character-w------" + shape_id_addition).height(1.0).width(line_thickness).rotate(-25.0).intersect(&shape("character-w-------" + shape_id_addition).width(0.45).height(0.4).y(-0.2))).build());
    set_character(u"x" + id_addition, &shape("character-x" + shape_id_addition).height(1.0).width(line_thickness).rotate(35.0).y(-0.125).intersect(&shape("character-x-" + shape_id_addition).width(0.5).height(0.55).y(-0.125)).add(&shape("character-x--" + shape_id_addition).height(1.0).width(line_thickness).rotate(-35.0).y(-0.125).intersect(&shape("character-x---" + shape_id_addition).width(0.5).height(0.55).y(-0.125))).build());
    set_character(u"y" + id_addition, &shape("character-y" + shape_id_addition).radius(0.2).height(0.4).thickness(thickness).y(0.05).subtract(&shape("character-y-" + shape_id_addition).width(0.8).height(0.5).y(0.4)).add(&shape("character-y--" + shape_id_addition).height(0.8).radius(0.2).thickness(thickness).subtract(&shape("character-y---" + shape_id_addition).height(1.0).width(1.0).y(0.65)).subtract(&shape("character-y----" + shape_id_addition).height(0.9).width(0.5).x(-0.2))).build());
    set_character(u"z" + id_addition, &shape("character-z" + shape_id_addition).height(1.0).width(line_thickness).y(-0.125).rotate(-45.5).intersect(&shape("character-z-" + shape_id_addition).width(0.5).height(0.55).y(-0.125)).add(&shape("character-z--" + shape_id_addition).width(0.5).height(line_thickness).y(0.1)).add(&shape("character-z---" + shape_id_addition).width(0.5).height(line_thickness).y(-0.35)).build());
    set_character(u"ä" + id_addition, &shape("character-ä" + shape_id_addition).radius(0.2).height(0.05).thickness(thickness).y(-0.125).add(&shape("character-ä-" + shape_id_addition).height(0.55).width(line_thickness).y(-0.125).x(0.2)).add(&shape("character-ä--" + shape_id_addition).width(line_thickness).height(line_thickness).x(-0.125).y(0.3)).add(&shape("character-ä---" + shape_id_addition).width(line_thickness).height(line_thickness).x(0.125).y(0.3)).build());
    set_character(u"ö" + id_addition, &shape("character-ö" + shape_id_addition).radius(0.2).height(0.05).thickness(thickness).y(-0.125).add(&shape("character-ö-" + shape_id_addition).width(line_thickness).height(line_thickness).x(-0.125).y(0.3)).add(&shape("character-ö--" + shape_id_addition).width(line_thickness).height(line_thickness).x(0.125).y(0.3)).build());
    set_character(u"ü" + id_addition, &shape("character-ü" + shape_id_addition).radius(0.2).height(0.4).thickness(thickness).y(0.05).subtract(&shape("character-ü-" + shape_id_addition).width(0.8).height(0.5).y(0.4)).add(&shape("character-ü--" + shape_id_addition).height(0.55).width(line_thickness).y(-0.125).x(0.2)).add(&shape("character-ü---" + shape_id_addition).width(line_thickness).height(line_thickness).x(-0.125).y(0.3)).add(&shape("character-ü----" + shape_id_addition).width(line_thickness).height(line_thickness).x(0.125).y(0.3)).build());
    set_character(u"A" + id_addition, &shape("character-A" + shape_id_addition).width(0.2).height(line_thickness).y(-0.1).add(&shape("character-A-" + shape_id_addition).height(0.9).width(line_thickness).rotate(-12.0).x(-0.1).intersect(&shape("character-A--" + shape_id_addition).width(0.5).height(0.8))).add(&shape("character-A---" + shape_id_addition).height(0.9).width(line_thickness).rotate(12.0).x(0.1).intersect(&shape("character-A----" + shape_id_addition).width(0.5).height(0.8))).build());
    set_character(u"B" + id_addition, &shape("character-B" + shape_id_addition).height(0.8).width(line_thickness).x(-0.2).add(&shape("character-B-" + shape_id_addition).width(0.5).radius(0.15).thickness(thickness).y(0.2).x(-0.25).intersect(&shape("character-B--" + shape_id_addition).width(0.5).height(0.8))).add(&shape("character-B---" + shape_id_addition).width(0.5).radius(0.2).thickness(thickness).y(-0.15).x(-0.25).intersect(&shape("character-B----" + shape_id_addition).width(0.5).height(0.8))).build());
    set_character(u"C" + id_addition, &shape("character-C" + shape_id_addition).radius(0.2).height(0.3).thickness(thickness).subtract(&shape("character-C-" + shape_id_addition).height(0.5).width(0.5).x(0.3).rotate(45.0)).build());
    set_character(u"D" + id_addition, &shape("character-D" + shape_id_addition).height(0.8).width(line_thickness).x(-0.2).add(&shape("character-D-" + shape_id_addition).width(0.5).height(0.3).radius(0.2).thickness(thickness).x(-0.25).intersect(&shape("character-D--" + shape_id_addition).width(0.5).height(0.8))).build());
    set_character(u"E" + id_addition, &shape("character-E" + shape_id_addition).width(line_thickness).height(0.8).x(-0.2).add(&shape("character-E-" + shape_id_addition).width(0.5).height(line_thickness).y(0.35)).add(&shape("character-E--" + shape_id_addition).width(0.4).height(line_thickness).x(-0.05)).add(&shape("character-E---" + shape_id_addition).width(0.5).height(line_thickness).y(-0.35)).build());
    set_character(u"F" + id_addition, &shape("character-F" + shape_id_addition).width(line_thickness).height(0.8).x(-0.2).add(&shape("character-F-" + shape_id_addition).width(0.5).height(line_thickness).y(0.35)).add(&shape("character-F--" + shape_id_addition).width(0.4).height(line_thickness).x(-0.05)).build());
    set_character(u"G" + id_addition, &shape("character-G" + shape_id_addition).radius(0.2).height(0.3).thickness(thickness).subtract(&shape("character-G-" + shape_id_addition).height(0.2).width(0.3).x(0.2).y(0.1)).add(&shape("character-G--" + shape_id_addition).height(line_thickness).width(0.25).x(0.125).y(-0.05)).build());
    set_character(u"H" + id_addition, &shape("character-H" + shape_id_addition).width(line_thickness).height(0.8).x(-0.2).add(&shape("character-H-" + shape_id_addition).width(line_thickness).height(0.8).x(0.2)).add(&shape("character-H--" + shape_id_addition).width(0.5).height(line_thickness)).build());
    set_character(u"I" + id_addition, &shape("character-I" + shape_id_addition).height(0.8).width(line_thickness).add(&shape("character-I-" + shape_id_addition).width(0.3).height(line_thickness).y(0.35)).add(&shape("character-I--" + shape_id_addition).width(0.3).height(line_thickness).y(-0.35)).build());
    set_character(u"J" + id_addition, &shape("character-J" + shape_id_addition).height(0.8).radius(0.2).thickness(thickness).y(0.25).intersect(&shape("character-J-" + shape_id_addition).width(0.5).height(0.8)).subtract(&shape("character-J--" + shape_id_addition).width(0.5).height(0.8).y(0.3).x(-0.25)).add(&shape("character-J---" + shape_id_addition).width(0.3).height(line_thickness).x(0.1).y(0.35)).build());
    set_character(u"K" + id_addition, &shape("character-K" + shape_id_addition).height(0.8).width(line_thickness).x(-0.2).add(&shape("character-K-" + shape_id_addition).width(1.0).height(line_thickness).rotate(60.0).y(0.1).intersect(&shape("character-K--" + shape_id_addition).height(0.8).width(0.5))).add(&shape("character-K---" + shape_id_addition).width(1.0).height(line_thickness).rotate(-60.0).y(-0.1).intersect(&shape("character-K----" + shape_id_addition).height(0.4).width(0.5).y(-0.2))).build());
    set_character(u"L" + id_addition, &shape("character-L" + shape_id_addition).width(line_thickness).height(0.8).x(-0.2).add(&shape("character-L-" + shape_id_addition).width(0.5).height(line_thickness).y(-0.35)).build());
    set_character(u"M" + id_addition, &shape("character-M" + shape_id_addition).height(0.8).width(line_thickness).x(-0.2).add(&shape("character-M-" + shape_id_addition).height(0.8).width(line_thickness).x(0.2)).add(&shape("character-M--" + shape_id_addition).height(1.0).width(line_thickness).rotate(25.0).intersect(&shape("character-M---" + shape_id_addition).width(0.5).height(0.4).y(0.2))).add(&shape("character-M----" + shape_id_addition).height(1.0).width(line_thickness).rotate(-25.0).intersect(&shape("character-M-----" + shape_id_addition).width(0.5).height(0.4).y(0.2))).build());
    set_character(u"N" + id_addition, &shape("character-N" + shape_id_addition).height(0.8).width(line_thickness).x(-0.2).add(&shape("character-N-" + shape_id_addition).height(0.8).width(line_thickness).x(0.2)).add(&shape("character-N--" + shape_id_addition).height(1.0).width(line_thickness).rotate(25.0).intersect(&shape("character-N---" + shape_id_addition).width(0.5).height(0.8))).build());
    set_character(u"O" + id_addition, &shape("character-O" + shape_id_addition).radius(0.2).height(0.3).thickness(thickness).build());
    set_character(u"P" + id_addition, &shape("character-P" + shape_id_addition).height(0.8).width(line_thickness).x(-0.2).add(&shape("character-P-" + shape_id_addition).width(0.5).radius(0.2).thickness(thickness).y(0.15).x(-0.25).intersect(&shape("character-P--" + shape_id_addition).width(0.5).height(0.8))).build());
    set_character(u"Q" + id_addition, &shape("character-Q" + shape_id_addition).radius(0.2).height(0.3).thickness(thickness).add(&shape("character-Q-" + shape_id_addition).height(0.25).width(line_thickness).rotate(45.0).y(-0.275).x(0.125)).build());
    set_character(u"R" + id_addition, &shape("character-R" + shape_id_addition).height(0.8).width(line_thickness).x(-0.2).add(&shape("character-R-" + shape_id_addition).width(0.5).radius(0.2).thickness(thickness).y(0.15).x(-0.25).intersect(&shape("character-R--" + shape_id_addition).width(0.5).height(0.8))).add(&shape("character-R---" + shape_id_addition).width(1.0).height(line_thickness).rotate(-60.0).y(-0.1).intersect(&shape("character-R----" + shape_id_addition).height(0.4).width(0.5).y(-0.2))).build());
    set_character(u"S" + id_addition, &shape("character-S" + shape_id_addition).radius(0.175).width(0.5).thickness(thickness).y(-0.175).x(-0.225).intersect(&shape("character-S-" + shape_id_addition).width(0.5).height(0.8)).subtract(&shape("character-S--" + shape_id_addition).width(0.5).height(0.15).x(-0.275)).add(&shape("character-S---" + shape_id_addition).radius(0.175).width(0.5).thickness(thickness).y(0.175).x(0.225).intersect(&shape("character-S----" + shape_id_addition).width(0.5).height(0.8)).subtract(&shape("character-S-----" + shape_id_addition).width(0.5).height(0.15).x(0.275))).build());
    set_character(u"T" + id_addition, &shape("character-T" + shape_id_addition).height(line_thickness).width(0.5).y(0.35).add(&shape("character-T-" + shape_id_addition).width(line_thickness).height(0.8)).build());
    set_character(u"U" + id_addition, &shape("character-U" + shape_id_addition).radius(0.2).height(1.0).thickness(thickness).y(0.35).intersect(&shape("character-U-" + shape_id_addition).width(0.5).height(0.8)).build());
    set_character(u"V" + id_addition, &shape("character-V" + shape_id_addition).height(1.0).width(line_thickness).rotate(12.5).x(-0.1).intersect(&shape("character-V-" + shape_id_addition).width(0.5).height(0.8)).add(&shape("character-V--" + shape_id_addition).height(1.0).width(line_thickness).rotate(-12.5).x(0.1).intersect(&shape("character-V---" + shape_id_addition).width(0.5).height(0.8))).build());
    set_character(u"W" + id_addition, &shape("character-W" + shape_id_addition).height(0.8).width(line_thickness).rotate(2.5).x(-0.2).add(&shape("character-W-" + shape_id_addition).height(0.8).width(line_thickness).rotate(-2.5).x(0.2)).add(&shape("character-W--" + shape_id_addition).height(1.0).width(line_thickness).rotate(25.0).intersect(&shape("character-W---" + shape_id_addition).width(0.45).height(0.4).y(-0.2))).add(&shape("character-W----" + shape_id_addition).height(1.0).width(line_thickness).rotate(-25.0).intersect(&shape("character-W-----" + shape_id_addition).width(0.45).height(0.4).y(-0.2))).build());
    set_character(u"X" + id_addition, &shape("character-X" + shape_id_addition).height(1.0).width(line_thickness).rotate(25.0).intersect(&shape("character-X-" + shape_id_addition).width(0.5).height(0.8)).add(&shape("character-X--" + shape_id_addition).height(1.0).width(line_thickness).rotate(-25.0).intersect(&shape("character-X---" + shape_id_addition).width(0.5).height(0.8))).build());
    set_character(u"Y" + id_addition, &shape("character-Y" + shape_id_addition).height(1.0).width(line_thickness).rotate(25.0).intersect(&shape("character-Y-" + shape_id_addition).width(0.5).height(0.4).y(0.2)).add(&shape("character-Y--" + shape_id_addition).height(1.0).width(line_thickness).rotate(-25.0).intersect(&shape("character-Y---" + shape_id_addition).width(0.5).height(0.4).y(0.2))).add(&shape("character-Y----" + shape_id_addition).height(0.4).width(line_thickness).y(-0.2)).build());
    set_character(u"Z" + id_addition, &shape("character-Z" + shape_id_addition).height(1.0).width(line_thickness).rotate(-32.5).intersect(&shape("character-Z-" + shape_id_addition).width(0.5).height(0.8)).add(&shape("character-Z--" + shape_id_addition).width(0.5).height(line_thickness).y(0.35)).add(&shape("character-Z---" + shape_id_addition).width(0.5).height(line_thickness).y(-0.35)).build());
    set_character(u"Ä" + id_addition, &shape("character-Ä" + shape_id_addition).width(0.2).height(line_thickness).y(-0.1).add(&shape("character-Ä-" + shape_id_addition).height(0.9).width(line_thickness).rotate(-12.0).x(-0.1).intersect(&shape("character-Ä--" + shape_id_addition).width(0.5).height(0.8))).add(&shape("character-Ä---" + shape_id_addition).height(0.9).width(line_thickness).rotate(12.0).x(0.1).intersect(&shape("character-Ä----" + shape_id_addition).width(0.5).height(0.8))).add(&shape("character-Ä-----" + shape_id_addition).width(line_thickness).height(line_thickness).x(-0.125).y(0.5)).add(&shape("character-Ä------" + shape_id_addition).width(line_thickness).height(line_thickness).x(0.125).y(0.5)).build());
    set_character(u"Ö" + id_addition, &shape("character-Ö" + shape_id_addition).radius(0.2).height(0.3).thickness(thickness).add(&shape("character-Ö-" + shape_id_addition).width(line_thickness).height(line_thickness).x(-0.125).y(0.5)).add(&shape("character-Ö--" + shape_id_addition).width(line_thickness).height(line_thickness).x(0.125).y(0.5)).build());
    set_character(u"Ü" + id_addition, &shape("character-Ü" + shape_id_addition).radius(0.2).height(1.0).thickness(thickness).y(0.35).intersect(&shape("character-Ü-" + shape_id_addition).width(0.5).height(0.8)).add(&shape("character-Ü--" + shape_id_addition).width(line_thickness).height(line_thickness).x(-0.125).y(0.5)).add(&shape("character-Ü---" + shape_id_addition).width(line_thickness).height(line_thickness).x(0.125).y(0.5)).build());
    set_character(u"1" + id_addition, &shape("character-1" + shape_id_addition).height(0.8).width(line_thickness).add(&shape("character-1-" + shape_id_addition).width(0.4).height(line_thickness).y(-0.35)).add(&shape("character-1--" + shape_id_addition).width(line_thickness).height(0.5).rotate(-55.0).y(0.25).x(-0.175).intersect(&shape("character-1---" + shape_id_addition).width(0.4).height(0.8))).build());
    set_character(u"2" + id_addition, &shape("character-2" + shape_id_addition).height(line_thickness).width(0.5).y(-0.35).add(&shape("character-2-" + shape_id_addition).radius(0.2).height(0.5).thickness(thickness).rotate(-50.0).x(-0.2).y(-0.025).intersect(&shape("character-2--" + shape_id_addition).width(0.5).height(0.8))).build());
    set_character(u"3" + id_addition, &shape("character-3" + shape_id_addition).width(0.2).radius(0.175).thickness(thickness).y(-0.175).x(-0.125).add(&shape("character-3-" + shape_id_addition).width(0.2).radius(0.175).thickness(thickness).y(0.175).x(-0.125).intersect(&shape("character-3---" + shape_id_addition).height(0.8).width(0.5)).subtract(&shape("character-3----" + shape_id_addition).height(0.3).width(0.5).x(-0.4))).intersect(&shape("character-3-----" + shape_id_addition).height(0.8).width(0.5)).subtract(&shape("character-3------" + shape_id_addition).height(0.3).width(0.5).x(-0.4)).build());
    set_character(u"4" + id_addition, &shape("character-4" + shape_id_addition).height(0.8).width(line_thickness).x(0.1).add(&shape("character-4-" + shape_id_addition).width(0.5).height(line_thickness).y(-0.15)).add(&shape("character-4--" + shape_id_addition).width(line_thickness).height(0.65).rotate(-30.0).y(0.15).x(-0.05).intersect(&shape("character-4---" + shape_id_addition).width(0.7).height(0.8))).build());
    set_character(u"5" + id_addition, &shape("character-5" + shape_id_addition).width(0.25).radius(0.2).thickness(thickness).y(-0.15).x(-0.125).intersect(&shape("character-5-" + shape_id_addition).height(0.8).width(0.5)).add(&shape("character-5--" + shape_id_addition).height(0.4).width(line_thickness).x(-0.2).y(0.2)).add(&shape("character-5---" + shape_id_addition).width(0.45).height(line_thickness).y(0.35).x(-0.00)).build());
    set_character(u"6" + id_addition, &shape("character-6" + shape_id_addition).radius(0.2).height(0.3).thickness(thickness).subtract(&shape("character-6-" + shape_id_addition).height(0.5).width(0.5).x(0.2).y(-0.1)).add(&shape("character-6--" + shape_id_addition).radius(0.2).thickness(thickness).y(-0.15)).build());
    set_character(u"7" + id_addition, &shape("character-7" + shape_id_addition).width(0.5).height(line_thickness).y(0.35).add(&shape("character-7-" + shape_id_addition).width(line_thickness).height(1.0).rotate(-25.0).x(0.06).intersect(&shape("character-7--" + shape_id_addition).width(0.5).height(0.8))).build());
    set_character(u"8" + id_addition, &shape("character-8" + shape_id_addition).radius(0.175).width(0.05).thickness(thickness).y(-0.175).add(&shape("character-8-" + shape_id_addition).radius(0.175).thickness(thickness).y(0.175)).build());
    set_character(u"9" + id_addition, &shape("character-9" + shape_id_addition).radius(0.2).height(0.3).thickness(thickness).subtract(&shape("character-9-" + shape_id_addition).height(0.5).width(0.5).x(-0.2).y(0.1)).add(&shape("character-9--" + shape_id_addition).radius(0.2).thickness(thickness).y(0.15)).build());
    set_character(u"0" + id_addition, &shape("character-0" + shape_id_addition).radius(0.2).height(0.3).thickness(thickness).add(&shape("character-0-" + shape_id_addition).width(line_thickness).height(0.8).rotate(-45.0).intersect(&shape("character-0--" + shape_id_addition).radius(0.2).height(0.3))).build());
    set_character(u"ß" + id_addition, &shape("character-ß" + shape_id_addition).height(0.65).width(line_thickness).x(-0.2).y(-0.075).add(&shape("character-ß-" + shape_id_addition).width(0.1).radius(0.15).thickness(thickness).y(0.2).x(-0.0125).intersect(&shape("character-ß--" + shape_id_addition).width(0.5).height(0.8)).subtract(&shape("character-ß---" + shape_id_addition).width(0.4).height(0.5).x(-0.2))).add(&shape("character-ß----" + shape_id_addition).width(0.5).radius(0.2).thickness(thickness).y(-0.15).x(-0.25).intersect(&shape("character-ß-----" + shape_id_addition).width(0.5).height(0.8)).subtract(&shape("character-ß------" + shape_id_addition).width(0.4).height(1.0).x(-0.2))).build());
    set_character(u"!" + id_addition, &shape("character-!" + shape_id_addition).height(line_thickness).width(line_thickness).y(-0.35).add(&shape("character-!-" + shape_id_addition).height(0.6).width(line_thickness).y(0.1)).build());
    set_character(u"?" + id_addition, &shape("character-?" + shape_id_addition).height(line_thickness).width(line_thickness).y(-0.35).x(-0.15).add(&shape("character-?-" + shape_id_addition).radius(0.15).width(0.5).thickness(thickness).x(-0.275).y(0.2).intersect(&shape("character-?--" + shape_id_addition).width(0.4).height(0.5).y(0.15))).add(&shape("character-?---" + shape_id_addition).height(0.2).width(line_thickness).y(-0.1).x(-0.15)).build());
    set_character(u"-" + id_addition, &shape("character--" + shape_id_addition).height(line_thickness).width(0.5).build());
    set_character(u"+" + id_addition, &shape("character-+" + shape_id_addition).height(0.5).width(line_thickness).add(&shape("character-+-" + shape_id_addition).width(0.5).height(line_thickness)).build());
    set_character(u"*" + id_addition, &shape("character-*" + shape_id_addition).height(0.5).width(line_thickness).add(&shape("character-*-" + shape_id_addition).width(0.5).height(line_thickness).rotate(35.0)).add(&shape("character-*--" + shape_id_addition).width(0.5).height(line_thickness).rotate(-35.0)).build());
    set_character(u"/" + id_addition, &shape("character-/" + shape_id_addition).width(line_thickness).height(1.0).rotate(-26.0).intersect(&shape("character-/-" + shape_id_addition).width(0.5).height(0.8)).build());
    set_character(u"|" + id_addition, &shape("character-|" + shape_id_addition).width(line_thickness).height(0.8).build());
    set_character(u"\\" + id_addition, &shape("character-\\" + shape_id_addition).width(line_thickness).height(1.0).rotate(26.0).intersect(&shape("character-\\-" + shape_id_addition).width(0.5).height(0.8)).build());
    set_character(u"="+ id_addition, &shape("character-=" + shape_id_addition).height(line_thickness).width(0.5).y(0.1).add(&shape("character-=-" + shape_id_addition).height(line_thickness).width(0.5).y(-0.1)).build());
    set_character(u"<"+ id_addition, &shape("character-<" + shape_id_addition).height(line_thickness).width(0.8).y(0.1).rotate(22).intersect(&shape("character-<-" + shape_id_addition).width(0.5).height(0.8)).add(&shape("character-<--" + shape_id_addition).height(line_thickness).width(0.8).y(-0.1).rotate(-22).intersect(&shape("character-<---" + shape_id_addition).width(0.5).height(0.8))).build());
    set_character(u">"+ id_addition, &shape("character->" + shape_id_addition).height(line_thickness).width(0.8).y(0.1).rotate(-22).intersect(&shape("character->-" + shape_id_addition).width(0.5).height(0.8)).add(&shape("character->--" + shape_id_addition).height(line_thickness).width(0.8).y(-0.1).rotate(22).intersect(&shape("character->---" + shape_id_addition).width(0.5).height(0.8))).build());
    set_character(u"."+ id_addition, &shape("character-." + shape_id_addition).height(line_thickness).width(line_thickness).y(-0.35).build());
    set_character(u":"+ id_addition, &shape("character-:" + shape_id_addition).height(line_thickness).width(line_thickness).y(-0.35).add(&shape("character-:-" + shape_id_addition).height(line_thickness).width(line_thickness).y(0.1)).build());
    set_character(u","+ id_addition, &shape("character-," + shape_id_addition).height(line_thickness).width(line_thickness).y(-0.35).add(&shape("character-,-" + shape_id_addition).height(0.4).width(line_thickness).rotate(-22.0).y(-0.4).intersect(&shape("character-,--" + shape_id_addition).width(line_thickness).height(0.2).y(-0.45))).build());
    set_character(u";"+ id_addition, &shape("character-;" + shape_id_addition).height(line_thickness).width(line_thickness).y(-0.35).add(&shape("character-;-" + shape_id_addition).height(0.4).width(line_thickness).rotate(-22.0).y(-0.4).intersect(&shape("character-;--" + shape_id_addition).width(line_thickness).height(0.2).y(-0.45))).add(&shape("character-;---" + shape_id_addition).height(line_thickness).width(line_thickness).y(0.1)).build());
    set_character(u"_"+ id_addition, &shape("character-_" + shape_id_addition).height(line_thickness).width(0.5).y(-0.35).build());
    set_character(u"("+ id_addition, &shape("character-(" + shape_id_addition).radius(0.9).x(0.9).thickness(thickness).intersect(&shape("character-(-" + shape_id_addition).height(0.8).width(0.4)).build());
    set_character(u")"+ id_addition, &shape("character-)" + shape_id_addition).radius(0.9).x(-0.9).thickness(thickness).intersect(&shape("character-)-" + shape_id_addition).height(0.8).width(0.4)).build());
    set_character(u"["+ id_addition, &shape("character-[" + shape_id_addition).height(0.8).width(0.4).x(0.1).subtract(&shape("character-[-" + shape_id_addition).height(0.6).width(0.2).x(0.1)).intersect(&shape("character-[--" + shape_id_addition).height(0.8).width(0.2)).build());
    set_character(u"]"+ id_addition, &shape("character-]" + shape_id_addition).height(0.8).width(0.4).x(-0.1).subtract(&shape("character-]-" + shape_id_addition).height(0.6).width(0.2).x(-0.1)).intersect(&shape("character-]--" + shape_id_addition).height(0.8).width(0.2)).build());
    set_character(u"{"+ id_addition, &shape("character-{" + shape_id_addition).height(0.6).width(0.2).radius(0.1).x(0.125).subtract(&shape("character-{-" + shape_id_addition).height(0.5).width(0.1).radius(0.05).x(0.125)).add(&shape("character-{--" + shape_id_addition).height(line_thickness).width(0.15).x(-0.1)).intersect(&shape("character-{---" + shape_id_addition).height(0.8).width(0.3)).build());
    set_character(u"}"+ id_addition, &shape("character-}" + shape_id_addition).height(0.6).width(0.2).radius(0.1).x(-0.125).subtract(&shape("character-}-" + shape_id_addition).height(0.5).width(0.1).radius(0.05).x(-0.125)).add(&shape("character-}--" + shape_id_addition).height(line_thickness).width(0.15).x(0.1)).intersect(&shape("character-}---" + shape_id_addition).height(0.8).width(0.3)).build());

    set_default_shape_colour({255, 255, 255, 255});
}

_COMPONENT& text (string new_component_id, u16string characters, colour font_colour)
{
    u16string id_addition = to_u16string(font_colour.red) + to_u16string(font_colour.green) + to_u16string(font_colour.blue);

    if (!has_character(u"NULL" + id_addition)) throw runtime_error("\nERROR: A font with the colour" + to_string(font_colour.red) + "," + to_string(font_colour.green) + "," + to_string(font_colour.blue) + " has not been initialised.");

    component(new_component_id);
    u16string sub_string;
    _SHAPE* character;
    int current_slot = 0;
    int line_breaks = 0;
    int current_character = 0;
    float line_gap = 0;
    for (int i = 0; i < characters.length(); i++)
    {
        sub_string = characters.substr(i, 1);
        character = get_character(sub_string, font_colour);
        get_component(new_component_id).add(character).x(current_character, current_slot * 0.6f).y(current_character, line_gap);

        if (sub_string == u"\n")
        {
            current_slot = 0;
            line_breaks++;
            line_gap = -1.0f * line_breaks + line_breaks * -0.25f;
        }
        else current_slot += sub_string == u"\t" ? 2 : 1;

        current_character++;
    }
    return get_component(new_component_id);
}

void replace_text (string component_id, u16string new_text, colour new_colour)
{
    int old_size = get_component(component_id).get_shapes()->size();
    int new_size = new_text.length();
    if (old_size != new_size) throw runtime_error("\nERROR: The text of component '" + component_id + "' with length " + to_string(old_size) + " can not be replaced with text of length " + to_string(new_size) + ". The size has to be equal.");

    for (int i = 0; i < new_text.length(); i++)
    {
        get_component(component_id).replace(i, get_character(new_text.substr(i, 1), new_colour));
    }
}